######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 19 19:58:25 2012
######################################################################

TEMPLATE = app
TARGET = 
QT += declarative
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
